//Generic Form Actions
export const SHOW_FORM = "SHOW_FORM";
export const LOAD_MODEL = "LOAD_MODEL";
export const ADD_MODEL = "ADD_MODEL";
export const REMOVE_MODEL = "REMOVE_MODEL";
export const LOADING = "LOADING";

export const UPDATE_CONTROLS = "UPDATE_CONTROLS";

export const VALIDATION_START = "VALIDATION_START";
export const VALIDATION_SUCCESS = "VALIDATION_SUCCESS";
export const VALIDATION_END = "VALIDATION_END";
export const VALIDATION_FAILED = "VALIDATION_FAILED";

export const UPDATE_FORM_INPUT = "UPDATE_FORM_INPUT";
export const UPDATE_DEFAULT_INPUT = "UPDATE_DEFAULT_INPUT";
export const CLEAR_FORM_INPUT = "CLEAR_FORM_INPUT";
export const ADD_FORM_ATTRIBUTE = "ADD_FORM_ATTRIBUTE";
export const UPDATE_FORM_ATTRIBUTE = "UPDATE_FORM_ATTRIBUTE";
export const SUBMIT_FORM_INPUT = "SUBMIT_FORM_INPUT";
export const FORM_ERROR = "FORM_ERROR";
export const FORM_SUCCESS = "FORM_SUCCESS";
export const TOGGLE_POPUP = "TOGGLE_POPUP";
export const FORM_CTRL_INVALID = "FORM_CTRL_INVALID";
export const FORM_CTRLS_VALID = "FORM_CTRLS_VALID";
export const SET_START_TIME = "SET_START_TIME";
export const DESTROY_FORM_STORE = "DESTROY_FORM_STORE";
